name: {{app_name}}
services:
  {{app_name}}:
    image: owntracks/recorder
    ports:
      - 127.0.0.1:8083:8083
    volumes:
      - "${DOCKER_VOLUMES}/owntracks/config:/config"
      - "${DOCKER_VOLUMES}/owntracks/store:/store"
    restart: unless-stopped
    container_name: {{app_name}}
    environment:
      - "OTR_HOST={{ global.host }}"
      - "OTR_USER={{ owntracks.mqtt.user }}"
      - "OTR_PASS={{ owntracks.mqtt.password }}"
