version: "2.1"
services: 
  nocodb:
    image: "nocodb/nocodb:latest"
    ports: 
      - "8081:8080"
    restart: unless-stopped
    volumes: 
      - "${DOCKER_VOLUMES}/nocodb:/usr/app/data"
    env_file:
      - ./.env
    container_name: nocodb
