---
- name: Install Nix Packages
  hosts: unicorn, trinity, localhost
  vars_files:
    - data/packages.yml
  # roles:
  # - role: danielrolls.nix
  tasks:
    - name: Get nix-info
      shell: "nix-shell -p nix-info --command nix-info" 
      register: nix_info
    - name: Debug
      debug:
        var: nix_info.stdout 
    - include_tasks: ansible/tasks/nix-install.yml
      loop: "{{ nix_packages }}"
