---
- name: Setup Docker Things
  hosts: unicorn
  tasks:
    - name: Create Traefik Network
      shell: docker network create traefik-proxy || true
    - name: Traefic
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/traefik/docker-compose.yml
        app_name: Traefik
        files: ['apps/traefik/traefik.toml']
    - name: Deluge
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/deluge/docker-compose.yml
        app_name: Deluge
    - name: pi-hole
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/pihole/docker-compose.yml
        app_name: pihole
        files: [
          'apps/pihole/pihole.env',
          'apps/pihole/custom.list'
        ]
    - name: Jellyfin
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/jellyfin/docker-compose.yml
        app_name: jellyfin
    - name: Radarr
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/radarr/docker-compose.yml
        app_name: radarr
    - name: Heimdall
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/heimdall/docker-compose.yml
        app_name: heimdall
    - name: Sonarr
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/sonarr/docker-compose.yml
        app_name: sonarr
    - name: Netdata
      include_role:
        name: deploy-compose
      vars:
        compose_file: apps/netdata/docker-compose.yml
        app_name: netdata
