---
- name: Setup Docker Things
  hosts: unicorn
  vars_files:
    - data/docker_apps.yml
  tasks:
    - name: Create Traefik Network
      shell: docker network create traefik-proxy || true
    - include_tasks: ansible/tasks/docker-compose-deploy.yml
      loop: "{{ docker_apps }}"
      vars:
        app_name: "{{ item.app_name }}"
        compose_file: "{{ item.compose_file }}"
        files: "{{ item.files }}"
