---
- name: Setup Docker Things
  gather_facts: true
  hosts: localhost, unicorn
  vars_files:
    - data/docker_apps2.yml
  tasks:
    - name: Create Traefik Network
      shell: docker network create traefik-proxy || true
    - include_tasks: ansible/tasks/docker-compose-deploy.yml
      loop: "{{ lookup('dict', docker_apps) }}"
      vars:
        app_name: "{{ item.key }}"
        compose_file: "{{ item.value.compose_file }}"
        files: "{{ item.value.files | default([]) }}"
