- name: Install and Run Docker containers
  hosts: unicorn
  roles:
    - role: deploy-compose
      vars:
        compose_file: apps/deluge/docker-compose.yml
        app_name: Deluge
    - role: deploy-compose
      vars:
        compose_file: apps/pihole/docker-compose.yml
        app_name: pihole
        files: ['apps/pihole/pihole.env']
    - role: deploy-compose
      vars:
        compose_file: apps/jellyfin/docker-compose.yml
        app_name: Jellyfin
