---
- name: 
  hosts: unicorn
  tasks:
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/mediasort.sh
    # - include_tasks: ansible/tasks/systemd-setup.yml
    #   vars:
    #     script: scripts/reboot.sh
    #     timer: "*-*-* 05:00:00"
