---
- name: 
  hosts: unicorn
  vars_files:
    - .config/configs.yml
  tasks:
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/mediasort.sh
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/backup.py
        timer: "*-*-* 01:00:00"
        args: "{{ etcenv.DOCKER_VOLUMES }} homeassistant.log* " 
