---
- name: 
  hosts: unicorn
  vars_files:
    - .config/configs.yml
  tasks:
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/mediasort.sh
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/backup/borg_backup.sh
        timer: "*-*-* 01:00:00"
        args: "{{ etcenv.DOCKER_VOLUMES }}" 
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/backup/upload_borg_backups.sh
        timer: "*-*-* 03:00:00"
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/camera_capture.sh
        timer: "*:0/5"
        args: "{{ cameras.front }}"
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/rclone/rclone_copy.sh
        timer: "*:0/15"
        args: "{{ camera.images.src }} {{ camera.images.dest }}"
        job_name: "camera_images"
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/rclone/rclone_sync.sh
        timer: "*:0/1"
        args: "{{ camera.video.src }} {{ camera.video.dest }}"
        job_name: "camera_videos"