---
- name: 
  hosts: unicorn
  vars_files:
    - .config/configs.yml
  tasks:
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/mediasort.sh
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/backup/borg_backup.sh
        timer: "*-*-* 01:00:00"
        args: "{{ etcenv.DOCKER_VOLUMES }}" 
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/backup/remote_backup.sh
        timer: "*-*-* 02:00:00"
        args: "{{ backups.machina.user }} {{ backups.machina.ip }} {{ backups.machina.dir }}"
    - include_tasks: ansible/tasks/systemd-setup.yml
      vars:
        script: scripts/backup/upload_borg_backups.sh
        timer: "*-*-* 03:00:00"
