services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      # - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=Europe/Dublin
      - PUID=${UID}
      - PGID=${GID}
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - $DOCKER_VOLUMES/n8n/.n8n:/home/node/.n8n
      - $DOCKER_VOLUMES/n8n/local-files:/files
    user: "${UID}:${GID}"
