- id: '1684360628619'
  alias: Front Hall Light Motion
  description: ''
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.motion_hall_motion
      light_target:
        device_id: 7ae703bb06a00547fb42e92a2b860c05
      no_motion_wait: 10
- id: '1685567122005'
  alias: Stairs Light Motion
  description: ''
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.bottom_motion
      no_motion_wait: 120
      light_target:
        device_id: 81b8c31a53bb9e4e1db7304e9f9d1395
- id: '1688597408899'
  alias: Upstairs Hall Light Motion
  description: ''
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.upper_hall_motion
      no_motion_wait: 120
      light_target:
        device_id: 7797359adb13cb65aaaeb47d062533a4
- id: '1688598217438'
  alias: Kitchen Light Motion
  description: ''
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 120
      motion_entity: binary_sensor.kitchen_motion_motion
      light_target:
        device_id: 0b14b2277dfb29915c1b4c1c2c00f6b5
