---
version: "2"
services:
  homer-local:
    image: b4bz/homer
    container_name: homer-local
    volumes:
      - './:/www/assets/'
    ports:
      - 1111:8080
    user: 1000:1000
    restart: unless-stopped
