---
version: "2"
services:
  homer-local:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer-local
    volumes:
      - './:/www/assets/'
    ports:
      - 1111:8080
    user: 1000:1000 # default
    # environment:
      # - INIT_ASSETS=1 # default