version: "3.3"
services:
  rail.danieldevine.dev:
    build: .
    ports:
    - "10000:10000"
    volumes:
      - ./ports.conf:/etc/apache2/ports.conf
    restart: unless-stopped
    container_name: railapp

