version: '3'

services:
  reverse-proxy:
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`box.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.enable=true"
    networks: 
      - "traefik-proxy"
  
networks:
  "traefik-proxy":
    external: true