name: Mosquitto
services:
  Mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
      # - '9001:9001'
    volumes:
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
      - './mosquitto_pw.txt:/mosquitto/config/mosquitto_pw.txt'
      - '$DOCKER_VOLUMES/mosquitto/data:/mosquitto/data'
      - '$DOCKER_VOLUMES/mosquitto/logs:/mosquitto/log'
    image: eclipse-mosquitto
    networks:
      - mqtt

networks:
  mqtt:
    external: true
