services:
    {{app_name}}:
        container_name: {{app_name}}
        # ports:
        #     - 8084:80
        volumes:
            - $DOCKER_VOLUMES/rotki/data:/data
            - $DOCKER_VOLUMES/rotki/logs:/logs
        image: rotki/rotki:latest