name: Frigate
services:
  Frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:0.16.3
    shm_size: "128mb" # update for your cameras based on calculation above
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES}/frigate/config:/config:rw
      - ${DRIVE_STORAGE}/Frigate:/media/frigate
      - ./config.yml:/config/config.yml
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "127.0.0.1:8971:8971"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:8554:8554" # RTSP feeds
      - "127.0.0.1:8555:8555/tcp" # WebRTC over tcp
      - "127.0.0.1:8555:8555/udp" # WebRTC over udp
