services:
  HomeAssistant:
    image: "lscr.io/linuxserver/homeassistant:latest"
    container_name: homeassistant
    # network_mode: host
    privileged: true
    volumes:
      - "${DOCKER_VOLUMES}/hass/:/config"
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/Dublin
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    # devices:
    #   - /path/to/device:/path/to/device #optional
    restart: unless-stopped
    cap_add:
     - NET_ADMIN
     - NET_RAW
    networks:
      - "traefik-router"
      - "databases"

networks:
  "traefik-router":
    external: true
  "databases":
    external: true
