version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata.mediabox.local # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      - "traefik.http.routers.netdata.rule=Host(`netdata.local`)"
      - "traefik.http.routers.netdata.service=api@internal"
      - "traefik.http.routers.netdata.entrypoints=web"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
      - "traefik.http.routers.netdata.service=netdata"
      - "traefik.enable=true"
    networks: 
      - "traefik-proxy"
  
networks:
  "traefik-proxy":
    external: true

volumes:
  netdataconfig:
  netdatalib:
  netdatacache: