[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.tsresolver.tailscale]

[api]
  dashboard = true
  debug = false

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false

[log]
  level = "DEBUG"