---
version: "2"
services:
  homer-remote:
    image: b4bz/homer
    container_name: homer-remote
    volumes:
      - './:/www/assets/'
    ports:
      - 2222:8080
    user: 1000:1000
    restart: unless-stopped