---
version: "2"
services:
  homer-remote:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer-remote
    volumes:
      - './:/www/assets/'
    ports:
      - 2222:8080
    user: 1000:1000 # default