version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - "${HOME}/.config/heimdall/:/config"
    ports:
      - 11000:80
      # - 443:443
    restart: unless-stopped
    labels:
      - "traefik.http.routers.heimdall.rule=Host(`home.local`)"
      - "traefik.http.routers.heimdall.service=api@internal"
      - "traefik.http.routers.heimdall.entrypoints=web"
      - "traefik.http.services.heimdall.loadbalancer.server.port=11000"
      - "traefik.http.routers.heimdall.service=heimdall"
      - "traefik.enable=true"
    networks: 
      - "traefik-proxy"
  
networks:
  "traefik-proxy":
    external: true